### ISSUE TITLE
Restricted arsenal problem

### ISSUE THREAD

**Issue by Danny12224** [antoinebidault/DynamicCivilWar#3]
@bidass hey, this mod had loads of potential but our squad weren't able to unrestrict our arsenal despite having unrestricted arsenal set globally and turning off the restricted arsenal setting when we load into your mod (on the weather selection screen). Is this a bug that you're aware of? Any ideas please? Thanks in advance mate.

**Comment by antoinebidault** [comment]
Hi @Danny12224 , thanks for the issue reporting. I reproduce the issue in multiplayer. This sounds fine in singleplayer. I'm having a look to this issue. Probably a problem with shared configuration with the other connected clients.

**Comment by antoinebidault** [comment]
Ok, I had a look and the checkbox was not correctly mapped & shared with client. I corrected it in the last update
