### ISSUE TITLE
Feedback on the mod

### ISSUE THREAD

**Issue by Cubox-** [antoinebidault/DynamicCivilWar#4]
I wanted to post this in the Steam comments for the mod, but the characters limit stopped me.
Here is my feedback:

```
@Bidass
I tried the mod a bit as singleplayer, and this has a very high potential if some issues are fixed. Here is the list of issues/wishes, most important first.

1) Enemies surrendered will rebel
I love the fact that enemies will surrender, but I have some issues with that.
When you release a surrendered unit, they will become hostile again, and shoot you instantly, killing you. I'm assuming this is a bug, but I would assume that liberating them would make them harmless, maybe turn them into civilian without their combat gear and have they run away.
Also, the 15m delay, animation and cut scene when interrogating them is more of a bother than a cool feature. I usually just shoot in the head (because I can't liberate him) the guy while the animation is continuing, which makes him finish the animation, then die instantly.

2) Medical system / player revive / friendly AI revive.
Most scenarios have a "revive" system, where you are downed and the AI can get you back up, if they can reach you. Not having one makes combat really suck at times.
One of the best revive systems I have seen is the one implemented in Antistatis. The AI will get back to you, and even drag you to cover before healing you. They do this for anyone in the squad, automatically. Having this system here would be so great!

I also dislike the medvac system. It's long, not fun and currently broken. The heli will land, the unit will be replaced, but the wounded guy will never be dragged to the heli.
I would simply replace the system by doing this:
When an AI dies, (or bleedout with the revive system), let it die. Add as a reinforcement to be called for points, calling the heli, which will land and deliver "new" units, which are here to replace the dead.

Also, I would not move the AI back to the player base, but leave them in the firefight. Add an option to spawn missing AI back in the base (without the long landing of the heli).

3) ACE Integration
I only saw two problems with ACE, no earplugs and unable to disable mines. (Wither vanilla option or ACE)

4) Reputation
The only times I really noticed reputation was when I got it changed. But I never understood why.
You should add reputation to the bottom information, so you can track it. Also show the reason why modification is added or removed.

Those issues (especially the first two), made me stop playing the scenario. But if they are fixed, I think this would be the greatest mod ever made, with a fun and re playable (if other maps are available) mission.
Combat feels good, enemies surrendering is really good. Mines is a good touch.
```

**Comment by antoinebidault** [comment]
Thank you for your very detailed post.  

I noticed some bugs with ACE too (player respawn not working...), I am currently working on it. I totally missed the mines and the earplugs issues...

I didn't expect my custom reviving system to make people so confused... But, I totally agree with you : it is very buggy and needs a simpler implementation. An other simpler way to improve it is to make AI a bit more stronger than usual. In the last version, I made your teammates 3 times stronger than their enemies. As a consequence, your teammates will stay on your side a bit longer. 

I recently rebuild all the reputation system : every compound will have his own level of reputation. There will be lots of things to influence the compound reputation : shoot close to civilian, talk to them without the lowered weapon, ...etc...
 The reputation and player's action will influence the state of the compound : 
- Neutral (Default state)
- Occupied by enemy
- Massacred (In case they support your faction and you didn't protect them enough...),
- Under humanitary intervention 
- Secured by friendly forces
There will be a couple of enemy tracked vehicles with officers spawned randomly on the map who will try to influence or occupy random compounds (In a simulated way...). If the local reputation is bad, the civilian will take weapon to shoot at you behind your back...
I have plenty of new interesting ideas around this new system...

Another improvement is the config screen that has been totally rebuilt making possible to choose the faction you want to play. It will not more be dependent to 3CB or RHS addons. 

The next release is still needs heavy dev & testing to become playable.

**Comment by Cubox-** [comment]
I'm happy to help with feedback.

I recently came upon another revive system, made to be included in missions easily.
http://www.armaholic.com/page.php?id=24088

After using it in some other scenarios, this is a good option. You could even let the player pick the revive system they want to use (if you still include one of your implementation)

Let me know once the mission is ready for testing, I'll give it a try.

**Comment by antoinebidault** [comment]
The last version is released : 
https://steamcommunity.com/sharedfiles/filedetails/?id=1775053830
