### ISSUE TITLE
Feedback/question on Medvac 

### ISSUE THREAD

**Issue by exro** [antoinebidault/DynamicCivilWar#5]
Firstly, I really enjoy this scene so thank you for your efforts!!

On medvac it says, mark the position on the map, but I don't know how to do that. Please could you let me know what the process is? Sorry for noob question.

I've read cubox's comments and I agree with his first point, liberabing a hostile results in being instantly shot. I also unloaded a whole 20 rounds of 5.56 into his head and he didn't die...is this something I'm doing wrong?

**Comment by exro** [comment]
Looks like the Medivac option now works for me! It seems to open the map automatically and then the chopper arrives. I throw a smoke and boom it lands..Looks like it only re-enforces once though, is this the case?

**Comment by antoinebidault** [comment]
Thanks a lot for your feedback. 
I'm currently reworking completely the engine of the mod. The next release is coming shortly.
I completely remade the AI reviving script. You now are able to revive and drag your friendly unit directly. Your AI teammates are considerably skilled and reinforced (3x stronger than usual). The surrendering system has been improved too. It was a bit buggy.

**Comment by exro** [comment]
Can't wait, thank you.
