### ISSUE TITLE
Addons dependencies

### ISSUE THREAD

**Issue by diomedea** [antoinebidault/DynamicCivilWar#6]
Please note that this scenario couldn't load until had installed the 3CB Factions addon. Without it, shows a message "You cannot play/edit this mission; it is dependent on downloadable content that has been deleted. UK3CB_Factions_Equipment_Vests".

Please remove the dependency or update the description to show all required addons.

**Comment by antoinebidault** [comment]
The issue is corrected in the last version. Thanks for the report !
